// Generated by Tools/UI/build_icon_font.py from Tabler Icons 3.48.0 (MIT). Do not edit by hand.
namespace SafeMining
{
    public static class MiningIcons
    {
        public const string Safe = "\uEA67"; // circle-check
        public const string Warning = "\uEA06"; // alert-triangle
        public const string Closed = "\uF00E"; // barrier-block
        public const string Stop = "\uEC2E"; // hand-stop
        public const string Check = "\uEA5E"; // check
        public const string Cross = "\uEB55"; // x
        public const string Info = "\uEAC5"; // info-circle
        public const string Straight = "\uEA25"; // arrow-up
        public const string TurnLeft = "\uEA82"; // corner-up-left
        public const string TurnRight = "\uEA83"; // corner-up-right
        public const string UTurn = "\uEB77"; // arrow-back-up
        public const string Watch = "\uEA9A"; // eye
        public const string Walk = "\uEC87"; // walk
        public const string Route = "\uEB17"; // route
        public const string RouteFixed = "\uF194"; // route-off
        public const string Shuffle = "\uF000"; // arrows-shuffle
        public const string Controlled = "\uEC38"; // adjustments-horizontal
        public const string NoHazard = "\uEB22"; // shield-check
        public const string Dice = "\uF08F"; // dice-5
        public const string Broadcast = "\uF1E9"; // broadcast
        public const string Cpu = "\uEF8E"; // cpu
        public const string Schedule = "\uEE21"; // calendar-time
        public const string Disconnected = "\uF0A0"; // plug-connected-x
        public const string Clock = "\uEA70"; // clock
        public const string Distance = "\uF291"; // ruler-measure
        public const string Exposure = "\uECC6"; // alert-octagon
        public const string Play = "\uED46"; // player-play
        public const string Pause = "\uED45"; // player-pause
        public const string Restart = "\uEB13"; // refresh
        public const string Compare = "\uF296"; // arrows-diff
        public const string Download = "\uEA96"; // download
        public const string Back = "\uEA19"; // arrow-left
        public const string ChevronDown = "\uEA5F"; // chevron-down
        public const string ChevronRight = "\uEA61"; // chevron-right
        public const string Radio = "\uEF2D"; // radio
        public const string Vibration = "\uECD4"; // wave-sine
        public const string Map = "\uEAE7"; // map-2
        public const string Pin = "\uEAE8"; // map-pin
        public const string Exit = "\uEF4D"; // door-exit
        public const string Camera = "\uED22"; // video
        public const string Headlamp = "\uEA51"; // bulb
        public const string Glasses = "\uEE8A"; // eyeglass
        public const string Keyboard = "\uEBD6"; // keyboard
    }
}
