using UnityEngine;

namespace SafeMining
{
    // Shared UI tokens. Status colours follow ISO 3864 safety semantics and match the
    // in-world lights: green = safe/route, yellow = warning, red = closed. Blue is system data only.
    public static class MiningUiStyle
    {
        // The project renders in linear colour space, so UI alpha blends in linear light:
        // .95 reads as roughly an 80% dim; lower values leave bright HUD text and world signs legible.
        public static readonly Color Backdrop = Hex(0x0E1113, .95f);
        public static readonly Color Surface = Hex(0x161B1F); // Opaque: world signs and HUD must not show through.
        public static readonly Color SurfaceSunken = Hex(0x0E1113);
        public static readonly Color SurfaceRaised = Hex(0x1F262B);
        public static readonly Color Line = Hex(0x2C353B);
        public static readonly Color LineStrong = Hex(0x3A454C);
        public static readonly Color TextPrimary = Hex(0xE8ECEF);
        public static readonly Color TextSecondary = Hex(0x9AA5AD);
        public static readonly Color Safe = Hex(0x2FD27F);
        public static readonly Color Warning = Hex(0xFFC21A);
        public static readonly Color Danger = Hex(0xFF5A4E);
        public static readonly Color Info = Hex(0x5AA9FF);
        public static readonly Color OnSafe = Hex(0x0B2A1A);
        public static readonly Color OnWarning = Hex(0x3A2C00);
        public static readonly Color OnDanger = Hex(0x3D0B07);

        // Sizes in canvas reference units (1600x900). Nothing below Caption.
        public const int SizeDisplay = 44, SizeTitle = 28, SizeMetric = 34, SizeBody = 20, SizeCaption = 16;

        static Font body, strong, heading, numeric, icons;
        public static Font Body => body ?? (body = Load("Barlow-Regular"));
        public static Font Strong => strong ?? (strong = Load("Barlow-SemiBold"));
        public static Font Heading => heading ?? (heading = Load("BarlowSemiCondensed-SemiBold"));
        public static Font Numeric => numeric ?? (numeric = Load("JetBrainsMono-Medium"));
        // Subset Tabler Icons; glyph names live in MiningIcons (generated by Tools/UI/build_icon_font.py).
        public static Font Icons => icons ?? (icons = Load("TablerIcons"));

        static Font Load(string name)
        {
            var font = Resources.Load<Font>("Fonts/" + name);
            if (font == null) Debug.LogWarning("UI font missing: Resources/Fonts/" + name + ".ttf; using built-in font.");
            return font != null ? font : Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");
        }

        static Sprite rounded, circle;
        // 9-sliced rounded rectangle, generated once so no image asset is needed.
        public static Sprite Rounded => rounded ?? (rounded = Shape(32, 8, true));
        public static Sprite Circle => circle ?? (circle = Shape(64, 32, false));

        static Sprite Shape(int size, int radius, bool sliced)
        {
            var texture = new Texture2D(size, size, TextureFormat.RGBA32, false)
            { name = sliced ? "UI rounded rect" : "UI circle", filterMode = FilterMode.Bilinear, wrapMode = TextureWrapMode.Clamp };
            var pixels = new Color32[size * size];
            for (int y = 0; y < size; y++)
                for (int x = 0; x < size; x++)
                {
                    // Distance to the nearest rounded corner centre; inside the straight edges it is zero.
                    float cx = Mathf.Clamp(x + .5f, radius, size - radius), cy = Mathf.Clamp(y + .5f, radius, size - radius);
                    float d = Vector2.Distance(new Vector2(x + .5f, y + .5f), new Vector2(cx, cy));
                    byte a = (byte)(Mathf.Clamp01(radius - d + .5f) * 255);
                    pixels[y * size + x] = new Color32(255, 255, 255, a);
                }
            texture.SetPixels32(pixels); texture.Apply(false, true);
            var border = sliced ? new Vector4(radius, radius, radius, radius) : Vector4.zero;
            return Sprite.Create(texture, new Rect(0, 0, size, size), new Vector2(.5f, .5f), 100, 0, SpriteMeshType.FullRect, border);
        }

        public static Color Hex(int rgb, float alpha = 1)
            => new Color(((rgb >> 16) & 255) / 255f, ((rgb >> 8) & 255) / 255f, (rgb & 255) / 255f, alpha);
    }
}
