"""Builds the subset Tabler icon font and its C# name table for the Unity UI.

Usage (from the project root, needs `pip install fonttools`):
    python Tools/UI/build_icon_font.py

Add an icon by appending its Tabler name (https://tabler.io/icons) to ICONS and rerunning.
Outputs Assets/Resources/Fonts/TablerIcons.ttf and Assets/Scripts/MiningIcons.cs.
"""
import os
import re
import sys
import urllib.request

from fontTools import subset

VERSION = "3.48.0"  # Pinned so every rebuild uses the same glyphs.
BASE = f"https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@{VERSION}"
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CACHE = os.path.join(ROOT, "Temp", "tabler-icons-" + VERSION)
FONT_OUT = os.path.join(ROOT, "Assets", "Resources", "Fonts", "TablerIcons.ttf")
LICENSE_OUT = os.path.join(ROOT, "Assets", "Resources", "Fonts", "TablerIcons-LICENSE.txt")
CS_OUT = os.path.join(ROOT, "Assets", "Scripts", "MiningIcons.cs")

# C# name -> Tabler icon name. Keep icons meaningful: status, direction, action, data source.
ICONS = {
    "Safe": "circle-check", "Warning": "alert-triangle", "Closed": "barrier-block", "Stop": "hand-stop",
    "Check": "check", "Cross": "x", "Info": "info-circle",
    "Straight": "arrow-up", "TurnLeft": "corner-up-left", "TurnRight": "corner-up-right", "UTurn": "arrow-back-up",
    "Watch": "eye", "Walk": "walk", "Route": "route", "RouteFixed": "route-off",
    "Shuffle": "arrows-shuffle", "Controlled": "adjustments-horizontal", "NoHazard": "shield-check", "Dice": "dice-5",
    "Broadcast": "broadcast", "Cpu": "cpu", "Schedule": "calendar-time", "Disconnected": "plug-connected-x",
    "Clock": "clock", "Distance": "ruler-measure", "Exposure": "alert-octagon",
    "Play": "player-play", "Pause": "player-pause", "Restart": "refresh", "Compare": "arrows-diff",
    "Download": "download", "Back": "arrow-left", "ChevronDown": "chevron-down", "ChevronRight": "chevron-right",
    "Radio": "radio", "Vibration": "wave-sine", "Map": "map-2", "Pin": "map-pin", "Exit": "door-exit",
    "Camera": "video", "Headlamp": "bulb", "Glasses": "eyeglass", "Keyboard": "keyboard",
}


def fetch(name):
    os.makedirs(CACHE, exist_ok=True)
    path = os.path.join(CACHE, os.path.basename(name))
    if not os.path.exists(path):
        urllib.request.urlretrieve(f"{BASE}/{name}", path)
    return path


def main():
    css = open(fetch("dist/tabler-icons.css"), encoding="utf-8").read()
    codes = dict(re.findall(r'\.ti-([a-z0-9-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)"', css))
    missing = [tabler for tabler in ICONS.values() if tabler not in codes]
    if missing:
        sys.exit("Unknown Tabler icon names: " + ", ".join(missing))

    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ["*"]  # Keep copyright and licence name records.
    options.notdef_outline = True
    font = subset.load_font(fetch("dist/fonts/tabler-icons.ttf"), options)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=[int(codes[t], 16) for t in ICONS.values()])
    subsetter.subset(font)
    subset.save_font(font, FONT_OUT, options)
    with open(fetch("LICENSE"), encoding="utf-8") as src, open(LICENSE_OUT, "w", encoding="utf-8", newline="\n") as dst:
        dst.write(src.read())

    lines = [
        "// Generated by Tools/UI/build_icon_font.py from Tabler Icons " + VERSION + " (MIT). Do not edit by hand.",
        "namespace SafeMining",
        "{",
        "    public static class MiningIcons",
        "    {",
    ]
    lines += [f'        public const string {name} = "\\u{codes[tabler].upper()}"; // {tabler}' for name, tabler in ICONS.items()]
    lines += ["    }", "}", ""]
    with open(CS_OUT, "w", encoding="utf-8", newline="\n") as stream:
        stream.write("\n".join(lines))
    print(f"{len(ICONS)} icons -> {os.path.relpath(FONT_OUT, ROOT)} ({os.path.getsize(FONT_OUT)} bytes) and {os.path.relpath(CS_OUT, ROOT)}")


if __name__ == "__main__":
    main()
